name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'  # Hexo 支持的 Node.js 版本

      - name: Install Hexo and dependencies
        run: |
          chmod +x ./install.sh
          ./install.sh
          
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to GitHub Pages
        env:
          GIT_AUTH_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          git config --global user.email "ivhu@foxmail.com"
          git config --global user.name "ivhu"
          npx hexo deploy
